language: ruby
sudo: false

rvm:
- 2.7
- 2.6
- 2.5
- 2.4
- 2.3
- 2.2
- 2.1
- 2.0
- 1.9.3
- ruby-head
- jruby-head
- jruby-9.2.9.0

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3
    - rvm: jruby-head
    - rvm: jruby-9.2.9.0

